using System.Collections.Generic;

namespace AmplifyShaderEditor
{
	internal static class ASESettingsUndoCatalog
	{
		internal static void AddTo( List<ASEZHPatch> patches )
		{
			int index = 0;
			foreach( string[] row in Rows )
			{
				string head = row[ 0 ] + "\n\t\t{\n\t\t\t";
				patches.Add( new ASEZHPatch { Id = "settings-undo-" + index++, FileName = "UndoParentNode.cs",
					Description = "设置控件显示副本", Find = head + row[ 1 ], Replace = head + row[ 2 ], Marker = head + row[ 2 ] } );
			}
		}
		static readonly string[][] Rows =
		{
			new[] { "public string EditorGUILayoutStringField( string name, string value, params GUILayoutOption[] options )",
				"string newValue = EditorGUILayout.TextField( name, value, options );",
				"string newValue = EditorGUILayout.TextField( ASESettingsDisplay.Label( name ), value, options );" },
			new[] { "public string EditorGUILayoutTextField( GUIContent label, string text, params GUILayoutOption[] options )",
				"string newValue = EditorGUILayout.TextField( label, text, options );",
				"string newValue = EditorGUILayout.TextField( ASESettingsDisplay.Label( label ), text, options );" },
			new[] { "public string EditorGUILayoutTextField( string label, string text, params GUILayoutOption[] options )",
				"string newValue = EditorGUILayout.TextField( label, text, options );",
				"string newValue = EditorGUILayout.TextField( ASESettingsDisplay.Label( label ), text, options );" },
			new[] { "public Enum EditorGUILayoutEnumPopup( GUIContent label, Enum selected, params GUILayoutOption[] options )",
				"Enum newValue = EditorGUILayout.EnumPopup( label, selected, options );",
				"Enum newValue = ASELocale.LayoutEnumPopup( ASESettingsDisplay.Label( label ), selected, options );" },
			new[] { "public int EditorGUILayoutIntPopup( string label, int selectedValue, string[] displayedOptions, int[] optionValues, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.IntPopup( label, selectedValue, displayedOptions, optionValues, options );",
				"int newValue = EditorGUILayout.IntPopup( ASESettingsDisplay.Label( label ), selectedValue, ASELocale.TranslateArray( displayedOptions ), optionValues, options );" },
			new[] { "public int EditorGUILayoutPopup( string label, int selectedIndex, string[] displayedOptions, GUIStyle style, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.Popup( label, selectedIndex, displayedOptions, style, options );",
				"int newValue = EditorGUILayout.Popup( ASESettingsDisplay.Label( label ), selectedIndex, ASELocale.TranslateArray( displayedOptions ), style, options );" },
			new[] { "public int EditorGUILayoutPopup( GUIContent label, int selectedIndex, GUIContent[] displayedOptions, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.Popup( label, selectedIndex, displayedOptions, options );",
				"int newValue = EditorGUILayout.Popup( ASESettingsDisplay.Label( label ), selectedIndex, ASELocale.TranslateContents( displayedOptions ), options );" },
			new[] { "public int EditorGUILayoutPopup( GUIContent label, int selectedIndex, GUIContent[] displayedOptions, GUIStyle style, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.Popup( label, selectedIndex, displayedOptions, style, options );",
				"int newValue = EditorGUILayout.Popup( ASESettingsDisplay.Label( label ), selectedIndex, ASELocale.TranslateContents( displayedOptions ), style, options );" },
			new[] { "public bool EditorGUILayoutToggle( GUIContent label, bool value, params GUILayoutOption[] options )",
				"bool newValue = EditorGUILayout.Toggle( label, value, options );",
				"bool newValue = EditorGUILayout.Toggle( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public bool EditorGUILayoutToggle( string label, bool value, GUIStyle style, params GUILayoutOption[] options )",
				"bool newValue = EditorGUILayout.Toggle( label, value, style, options );",
				"bool newValue = EditorGUILayout.Toggle( ASESettingsDisplay.Label( label ), value, style, options );" },
			new[] { "public int EditorGUILayoutIntField( GUIContent label, int value, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.IntField( label, value, options );",
				"int newValue = EditorGUILayout.IntField( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public int EditorGUILayoutIntField( string label, int value, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.IntField( label, value, options );",
				"int newValue = EditorGUILayout.IntField( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public float EditorGUILayoutFloatField( GUIContent label, float value, params GUILayoutOption[] options )",
				"float newValue = EditorGUILayout.FloatField( label, value, options );",
				"float newValue = EditorGUILayout.FloatField( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public float EditorGUILayoutFloatField( string label, float value, params GUILayoutOption[] options )",
				"float newValue = EditorGUILayout.FloatField( label, value, options );",
				"float newValue = EditorGUILayout.FloatField( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public float EditorGUILayoutRangedFloatField( string label, float value, float min, float max, params GUILayoutOption[] options )",
				"float newValue = Mathf.Clamp( EditorGUILayout.FloatField( label, value, options ), min, max );",
				"float newValue = Mathf.Clamp( EditorGUILayout.FloatField( ASESettingsDisplay.Label( label ), value, options ), min, max );" },
			new[] { "public Color EditorGUILayoutColorField( string label, Color value, params GUILayoutOption[] options )",
				"Color newValue = EditorGUILayout.ColorField( label, value, options );",
				"Color newValue = EditorGUILayout.ColorField( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public Color EditorGUILayoutColorField( GUIContent label, Color value, bool showEyedropper, bool showAlpha, bool hdr, params GUILayoutOption[] options )",
				"Color newValue = EditorGUILayout.ColorField( label, value, showEyedropper, showAlpha, hdr, options );",
				"Color newValue = EditorGUILayout.ColorField( ASESettingsDisplay.Label( label ), value, showEyedropper, showAlpha, hdr, options );" },
			new[] { "public float EditorGUILayoutSlider( string label, float value, float leftValue, float rightValue, params GUILayoutOption[] options )",
				"float newValue = EditorGUILayout.Slider( label, value, leftValue, rightValue, options );",
				"float newValue = EditorGUILayout.Slider( ASESettingsDisplay.Label( label ), value, leftValue, rightValue, options );" },
			new[] { "public float EditorGUILayoutSlider( GUIContent label, float value, float leftValue, float rightValue, params GUILayoutOption[] options )",
				"float newValue = EditorGUILayout.Slider( label, value, leftValue, rightValue, options );",
				"float newValue = EditorGUILayout.Slider( ASESettingsDisplay.Label( label ), value, leftValue, rightValue, options );" },
			new[] { "public UnityEngine.Object EditorGUILayoutObjectField( string label, UnityEngine.Object obj, System.Type objType, bool allowSceneObjects, params GUILayoutOption[] options )",
				"UnityEngine.Object newValue = EditorGUILayout.ObjectField( label, obj, objType, allowSceneObjects, options );",
				"UnityEngine.Object newValue = EditorGUILayout.ObjectField( ASESettingsDisplay.Label( label ), obj, objType, allowSceneObjects, options );" },
			new[] { "public Vector2 EditorGUIVector2Field( Rect position, string label, Vector2 value )",
				"Vector2 newValue = EditorGUI.Vector2Field( position, label, value );",
				"Vector2 newValue = EditorGUI.Vector2Field( position, ASESettingsDisplay.Label( label ), value );" },
			new[] { "public Vector2 EditorGUILayoutVector2Field( string label, Vector2 value, params GUILayoutOption[] options )",
				"Vector2 newValue = EditorGUILayout.Vector2Field( label, value, options );",
				"Vector2 newValue = EditorGUILayout.Vector2Field( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public Vector3 EditorGUIVector3Field( Rect position, string label, Vector3 value )",
				"Vector3 newValue = EditorGUI.Vector3Field( position, label, value );",
				"Vector3 newValue = EditorGUI.Vector3Field( position, ASESettingsDisplay.Label( label ), value );" },
			new[] { "public Vector3 EditorGUILayoutVector3Field( string label, Vector3 value, params GUILayoutOption[] options )",
				"Vector3 newValue = EditorGUILayout.Vector3Field( label, value, options );",
				"Vector3 newValue = EditorGUILayout.Vector3Field( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public Vector4 EditorGUIVector4Field( Rect position, string label, Vector4 value )",
				"Vector4 newValue = EditorGUI.Vector4Field( position, label, value );",
				"Vector4 newValue = EditorGUI.Vector4Field( position, ASESettingsDisplay.Label( label ), value );" },
			new[] { "public Vector4 EditorGUILayoutVector4Field( string label, Vector4 value, params GUILayoutOption[] options )",
				"Vector4 newValue = EditorGUILayout.Vector4Field( label, value, options );",
				"Vector4 newValue = EditorGUILayout.Vector4Field( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public int EditorGUILayoutIntSlider( GUIContent label, int value, int leftValue, int rightValue, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.IntSlider( label, value, leftValue, rightValue, options );",
				"int newValue = EditorGUILayout.IntSlider( ASESettingsDisplay.Label( label ), value, leftValue, rightValue, options );" },
			new[] { "public int EditorGUILayoutIntSlider( string label, int value, int leftValue, int rightValue, params GUILayoutOption[] options )",
				"int newValue = EditorGUILayout.IntSlider( label, value, leftValue, rightValue, options );",
				"int newValue = EditorGUILayout.IntSlider( ASESettingsDisplay.Label( label ), value, leftValue, rightValue, options );" },
			new[] { "public bool EditorGUILayoutToggleLeft( GUIContent label, bool value, params GUILayoutOption[] options )",
				"bool newValue = EditorGUILayout.ToggleLeft( label, value, options );",
				"bool newValue = EditorGUILayout.ToggleLeft( ASESettingsDisplay.Label( label ), value, options );" },
			new[] { "public bool EditorGUILayoutFoldout( bool foldout, string content )",
				"bool newValue = EditorGUILayout.Foldout( foldout, content );",
				"bool newValue = EditorGUILayout.Foldout( foldout, ASESettingsDisplay.Label( content ) );" },
			new[] { "public bool EditorGUIFoldout( Rect position, bool foldout, string content )",
				"bool newValue = EditorGUI.Foldout( position, foldout, content );",
				"bool newValue = EditorGUI.Foldout( position, foldout, ASESettingsDisplay.Label( content ) );" },
			new[] { "public string EditorGUITextField( Rect position, string label, string text )",
				"string newValue = EditorGUI.TextField( position, label, text );",
				"string newValue = EditorGUI.TextField( position, ASESettingsDisplay.Label( label ), text );" },
			new[] { "public string EditorGUITextField( Rect position, string label, string text, [UnityEngine.Internal.DefaultValue( \"EditorStyles.textField\" )] GUIStyle style )",
				"string newValue = EditorGUI.TextField( position, label, text, style );",
				"string newValue = EditorGUI.TextField( position, ASESettingsDisplay.Label( label ), text, style );" },
			new[] { "public Color EditorGUIColorField( Rect position, GUIContent label, Color value, bool showEyedropper, bool showAlpha, bool hdr )",
				"Color newValue = EditorGUI.ColorField( position, label, value, showEyedropper, showAlpha, hdr );",
				"Color newValue = EditorGUI.ColorField( position, ASESettingsDisplay.Label( label ), value, showEyedropper, showAlpha, hdr );" },
			new[] { "public Color EditorGUIColorField( Rect position, string label, Color value )",
				"Color newValue = EditorGUI.ColorField( position, label, value );",
				"Color newValue = EditorGUI.ColorField( position, ASESettingsDisplay.Label( label ), value );" },
			new[] { "public int EditorGUIIntField( Rect position, string label, int value )",
				"int newValue = EditorGUI.IntField( position, label, value );",
				"int newValue = EditorGUI.IntField( position, ASESettingsDisplay.Label( label ), value );" },
			new[] { "public int EditorGUIIntField( Rect position, string label, int value, [UnityEngine.Internal.DefaultValue( \"EditorStyles.numberField\" )] GUIStyle style )",
				"int newValue = EditorGUI.IntField( position, label, value, style );",
				"int newValue = EditorGUI.IntField( position, ASESettingsDisplay.Label( label ), value, style );" },
			new[] { "public float EditorGUIFloatField( Rect position, string label, float value )",
				"float newValue = EditorGUI.FloatField( position, label, value );",
				"float newValue = EditorGUI.FloatField( position, ASESettingsDisplay.Label( label ), value );" },
			new[] { "public float EditorGUIFloatField( Rect position, string label, float value, [UnityEngine.Internal.DefaultValue( \"EditorStyles.numberField\" )] GUIStyle style )",
				"float newValue = EditorGUI.FloatField( position, label, value, style );",
				"float newValue = EditorGUI.FloatField( position, ASESettingsDisplay.Label( label ), value, style );" },
			new[] { "public int EditorGUIIntPopup( Rect position, int selectedValue, GUIContent[] displayedOptions, int[] optionValues, [UnityEngine.Internal.DefaultValue( \"EditorStyles.popup\" )] GUIStyle style )",
				"int newValue = EditorGUI.IntPopup( position, selectedValue, displayedOptions, optionValues, style );",
				"int newValue = EditorGUI.IntPopup( position, selectedValue, ASELocale.TranslateContents( displayedOptions ), optionValues, style );" },
			new[] { "public int EditorGUIPopup( Rect position, string label, int selectedIndex, string[] displayedOptions )",
				"int newValue = EditorGUI.Popup( position, label, selectedIndex, displayedOptions );",
				"int newValue = EditorGUI.Popup( position, ASESettingsDisplay.Label( label ), selectedIndex, ASELocale.TranslateArray( displayedOptions ) );" },
			new[] { "public int EditorGUIPopup( Rect position, int selectedIndex, GUIContent[] displayedOptions, [UnityEngine.Internal.DefaultValue( \"EditorStyles.popup\" )] GUIStyle style )",
				"int newValue = EditorGUI.Popup( position, selectedIndex, displayedOptions, style );",
				"int newValue = EditorGUI.Popup( position, selectedIndex, ASELocale.TranslateContents( displayedOptions ), style );" },
			new[] { "public int EditorGUIPopup( Rect position, int selectedIndex, string[] displayedOptions, [UnityEngine.Internal.DefaultValue( \"EditorStyles.popup\" )] GUIStyle style )",
				"int newValue = EditorGUI.Popup( position, selectedIndex, displayedOptions, style );",
				"int newValue = EditorGUI.Popup( position, selectedIndex, ASELocale.TranslateArray( displayedOptions ), style );" },
			new[] { "public int EditorGUIIntPopup( Rect position, int selectedValue, string[] displayedOptions, int[] optionValues, [UnityEngine.Internal.DefaultValue( \"EditorStyles.popup\" )] GUIStyle style )",
				"int newValue = EditorGUI.IntPopup( position, selectedValue, displayedOptions, optionValues, style );",
				"int newValue = EditorGUI.IntPopup( position, selectedValue, ASELocale.TranslateArray( displayedOptions ), optionValues, style );" },
			new[] { "public bool EditorGUIToggle( Rect position, string text, bool value )",
				"bool newValue = EditorGUI.Toggle( position,text, value );",
				"bool newValue = EditorGUI.Toggle( position,ASESettingsDisplay.Label( text ), value );" },
			new[] { "public bool GUILayoutToggle( bool value, string text, GUIStyle style, params GUILayoutOption[] options )",
				"bool newValue = GUILayout.Toggle( value, text, style, options );",
				"bool newValue = GUILayout.Toggle( value, ASESettingsDisplay.Label( text ), style, options );" },
			new[] { "public bool GUILayoutButton( string text, GUIStyle style, params GUILayoutOption[] options )",
				"bool value = GUILayout.Button( text, style, options );",
				"bool value = GUILayout.Button( ASESettingsDisplay.Label( text ), style, options );" },
		};
	}
}
